//
//  Artist.swift
//  visionProMusicApp
//
//  Created by Antonin Simon on 16/05/2024.
//

import Foundation


struct Artist: Identifiable, Equatable {
    var id = UUID()
    var name: String
    var image: String?
    var followers: Int?
    var listenings: Int?
    var worldRanking: Int?
    var description: String?
    
    func getAllSongs() -> [Song] {
        songs.filter{ $0.album.artist.id == self.id }
    }
    
    func getAllAlbums() -> [Album] {
        albums.filter{ $0.artist.id == self.id }
    }
}

let artists: [Artist] = [
    Artist(name: "Nekfeu", 
           image: "https://i.postimg.cc/xTh5SD8j/NEKFEU.png",
           followers: 2694896,
           listenings: 3095866,
           description: """
           A member of hip-hop acts including S-Crew, 1995, and L'Entourage, Nekfeu is known for both political and personal subject matter. He became a chart-topping solo artist in his native France with his second album, 2016's Cyborg. A year later, he made his film acting debut in Tout Nous Sépare opposite the legendary Catherine Deneuve.
           
           Born Ken Samarás in La Trinité, Alpes-Maritimes, Nekfeu's status in the Paris rap scene rose as he participated in open-mike battles as a young teen. He eventually recorded his first album as part of the group S-Crew, which released Même Signature in 2010. Still a member of S-Crew, he also joined 1995, which issued La Source in 2011, and another one of his groups, 5 Majeur, put out a self-titled album the same year. All three projects released follow-ups: S-Crew's Métamorphose and 1995's La Suite both arrived in 2012, while 5 Majeur's Variations saw release in 2013. He continued to record with multiple groups; S-Crew delivered third album Seine Zoo, and 1995 issued Paris Sud Minute, both in 2013. Nekfeu formed yet another collaborative hip-hop act, L'Entourage, for the 2014 long-player Jeunes Entrepreneurs.
           
           Nekfeu released his first solo album, Feu, on Seine Zoo Records in 2015. It went to number three on the French album chart and number five in Switzerland on its way to winning a Victoire award for Urban Music Album of the Year. His second solo release, Cyborg, arrived in late 2016 and went all the way to number one in France. That year also brought a fourth S-Crew album, Destins Liés.
           """
          ),
    Artist(name: "Tyler, The Creator", 
           image: "https://i.postimg.cc/g0qHRxDr/TYLER.png",
           followers: 15278031,
           listenings: 33734881,
           worldRanking: 125,
           description: """
            Tyler, The Creator is a rapper and producer distinguished above all other singular qualities by his gravelly voice and an irascible disposition befitting a collision-shop owner. He appeared in the late 2000s as a founding member of Odd Future, an outlandish teenaged alternative rap crew that gradually permeated the mainstream as it begat a multitude of related projects. Most of these recordings, including Earl Sweatshirt's Earl, Odd Future's Top Ten The OF Tape, Vol. 2, and Franck Ocean's Grammy-winning Channel Orange, were made with Tyler's deep involvement. Amid this whirlwind, Tyler started building a solo discography that has gleefully swung from purposefully distasteful and crude to charming and sophisticated, sometimes blurring the distinction between the extremes. Goblin (2011), Wolf (2013), Cherry Bomb (2015), and Flower Boy (2017), his first four solo albums, all debuted within the Top Five of the Billboard 200. The widespread embrace of the kaleidoscopic Flower Boy, a number two hit nominated for a Grammy in the category of Best Rap Album, led to chart-topping, Grammy-winning success with IGOR (2019) and CALL ME IF YOU GET LOST (2021). The latter lengthened Tyler's stylistic reach while reaffirming his devotion to hip-hop with a raw lyrical approach.
            
            Tyler Okonma was born and raised in Los Angeles County, splitting time in Ladera Heights and nearby Hawthorne. He got his first taste of fame when the Los Angeles Times ran a "teen on the street"-type story on the then-16-year-old skateboarding enthusiast, who was also interested in music and fashion. Around this time, Tyler began making music with Odd Future's other core members, and in 2009 released a solo mixtape titled Bastard. By the end of the following year, OF's surreal and filthy material, epitomized by Earl Sweatshirt's mixtape Earl -- most of which Tyler produced -- had earned them a loyal following. It was during that year that a video Tyler directed for the OF track "French" took off, topping a million views by December and drawing attention to a slew of additional crew-related mixtapes that followed.
            
            Signed as a solo artist to a one-album deal with XL Recordings, Tyler made his proper solo debut with Goblin. Upon its May 2011 arrival, the album became the first Odd Future-related product to be released through the traditional music-industry channels, and debuted at number five on the Billboard 200. Meanwhile, Tyler continued to produce for OF and its affiliates, most notably on The OF Tape, Vol. 2 and a later 2012 release, Frank Ocean's Channel Orange, which won a Grammy for Best Urban Contemporary Album. Tyler's second LP, Wolf, followed on the Odd Future label in April 2013. It entered the Billboard 200 at number three with an expansive list of guests -- including Erykah Badu, Pharell, Stereolab's Laetita Sadier, and Quadron's Coco O -- reflective of Tyler's aesthetic.
            
            Tyler's third proper album, Cherry Bomb, another Odd Future label offering, leaked to online streaming services before its official April 2015 release date. It nonetheless became the artist's third consecutive Top Ten entry, enhanced with uncredited guest appearances from Kanye West and Lil Wayne. Tyler's number of productions and guest appearances subsequently continued to increase through collaborations with Ocean, fellow OF associates the Internet and Domo Genesis, and A$AP Mob. Flower Boy, his acclaimed fourth solo album, was issued through Columbia in July 2017. The LP landed at number two on the Billboard 200 and was later nominated for Best Rap Album at the 60th Annual Grammy Awards.
            
            The following year, Tyler released a small batch of non-album singles, as well as the EP-length and unsurprisingly animated Music Inspired by Illumination & Dr. Seuss' the Grinch. The proper follow-up to Flower Boy, the thoroughly heartsick IGOR, arrived in May 2019. It debuted on the Billboard 200 at number one and earned Tyler a Grammy for Best Rap Album. Collaborations in 2020 with Westside Gunn, Freddie Gibs, and Lil Yachty set the stage for his sixth solo LP. CALL ME IF YOU GET LOST, hosted by Gangsta Grillz mixtape don DJ Drama, offered some of Tyler's toughest beats and rhymes while incorporating synth pop and reggae deviations. Issued in June 2021, the album put Tyler back on top of the Billboard 200 and spawned the Hot 100 hit "WusYaName," featuring YoungBoy Never Broke Again and Ty Dolla $ign. It also made Tyler a repeat Grammy winner of Best Rap Album. CALL ME IF YOU GET LOST: The Estate Sale, an expanded version of the album featuring eight additional tracks, appeared in 2023. ~ Andy Kellman, Rovi
            """
          
          ),
    Artist(name: "Nirvana", 
           image: "https://i.postimg.cc/L4yvNZM1/NIRVANA.png",
           followers: 19569556,
           listenings: 31415420,
           worldRanking: 140,
           description: """
            Nothing was ever quite the same after Nirvana. The band's second album, 1991's Nevermind, revolutionized popular music by bringing alternative rock above ground, introducing mainstream audiences to sounds and concepts that had previously existed only in shadowy record store corners and on low-frequency college radio airwaves. Nevermind's noisy, dissonant guitar rock, mumbled or howled surrealistic lyrics, and generally angsty punk attitudes were unlikely candidates for chart success, but the band undercut their grungy songs with enough pop melodicism to create a sound unlike anything average listeners had ever heard before, striking at the exact right moment to become an unprecedented success.

            Since Nirvana were rooted in an indie aesthetic but loved pop music, they fought their stardom while courting it, becoming some of the most notorious anti-rock stars in history. They consciously attempted to shed their audience with 1993's abrasive, Steve Albini-produced third album In Utero, but vocalist/guitarist/songwriter Kurt Cobain's growing mental health and substance abuse issues led to his death by suicide in 1994. Though Nirvana's story was cut tragically short, their legacy stands as one of the most influential in rock & roll history.

            Kurt Cobain (vocals, guitar) met Chris Novoselic (born Krist Novoselic) (bass) in 1985 in Aberdeen, Washington, a small logging town 100 miles away from Seattle. While Novoselic came from a relatively stable background, Cobain's childhood had been thrown into turmoil when his parents divorced when he was eight. Following the divorce, he lived at the homes of various relatives, developing a love for the Beatles and then heavy metal in the process. Eventually, American hardcore punk worked its way into dominating his listening habits and he met the Melvins, an Olympia-based underground heavy punk band. Cobain began playing in punk bands like Fecal Matter, often with the Melvins' bassist Dale Crover. Through the Melvins' leader, Buzz Osborne, Cobain met Novoselic, who also had an intense interest in punk, which meant that he, like Cobain, felt alienated from the macho, redneck population of Aberdeen. The duo decided to form a band called the Stiff Woodies, with Cobain on drums, Novoselic on bass, and a rotating cast of guitarists and vocalists. The group went through name changes as quickly as guitarists, before deciding that Cobain would play guitar and sing. Renamed Skid Row, the new trio featured drummer Aaron Burkhart, who left the band by the end of 1986 and was replaced by Chad Channing. By 1987, the band was called Nirvana.

            Nirvana began playing parties in Olympia, gaining a cult following. Around 1987, the band made ten demos with producer Jack Endino, who played the recordings to Jonathan Poneman, one of the founders of the Seattle-based indie label Sub Pop. Poneman signed Nirvana, and in December of 1988, the band released its first single, a cover of Shocking Blue's "Love Buzz." Sub Pop orchestrated an effective marketing scheme, which painted the band as backwoods, logging-town hicks, which irritated Cobain and Novoselic. While "Love Buzz" was fairly well-received, the band's debut album, Bleach, was what got the ball rolling. Recorded for just over $600 and released in June 1989, Bleach slowly became a hit on college radio, due to the group's consistent touring. Though Jason Everman was credited as a second guitarist on the sleeve of Bleach, he didn't appear on the record; he only toured in support of the album before leaving the band at the end of the year to join Soundgarden and then Mindfunk. Bleach sold 35,000 copies and Nirvana became favorites of college radio, the British weekly music press, and Sonic Youth, Mudhoney, and Dinosaur Jr., which was enough to attract the attention of major labels.

            In July 1990, Nirvana recorded "Sliver"/"Dive" with Mudhoney drummer Dan Peters on drums and producer Butch Vig. The band also made a six-song demo with Vig, which was shopped to major labels, who soon began competing to sign the group. In August, they hit the road with Sonic Youth's Goo tour (including Crover on drums). That September, Dave Grohl, formerly of the D.C.-based hardcore band Scream, became Nirvana's drummer and the band signed with DGC for $287,000. Nirvana recorded their second album with Vig, completing the record in June of 1991. Nevermind was released in September, supported by a quick American tour. While DGC was expecting a moderately successful release, in the neighborhood of 100,000 copies, Nevermind immediately became a smash hit, quickly selling out its initial shipment of 50,000 copies and creating a shortage across America. What helped the record become a success was "Smells Like Teen Spirit," a blistering four-chord rocker that was accompanied by a video that shot into heavy MTV rotation. By the beginning of 1992, "Smells Like Teen Spirit" had climbed into the American Top Ten and Nevermind bumped Michael Jackson's much-touted comeback album Dangerous off the top of the album charts; it reached the British Top Ten shortly afterward. By February, the album had been certified triple platinum.

            Nirvana's success took the music industry by surprise, Nirvana included. From the moment Nirvana were met with mainstream visibility, Cobain used his newfound fame to relentlessly push his favorite independent artists as if their music was more important than his own. This took the form of bringing Japanese alt-pop trio Shonen Knife on tour, covering lesser-known but formative artists like the Wipers, the Vaselines, and Meat Puppets, or wearing a homemade Daniel Johnston t-shirt during television appearances and high-profile concerts. Cobain's enthusiastic fandom introduced untold numbers of Nirvana fans to artists they most likely wouldn't have known to seek out on their own, and in the process, energized those artists' careers.
            """
          ),
    Artist(name: "Daft Punk", 
           image: "https://i.postimg.cc/SNJd5Nyt/DAFTPUNK.png",
           followers: 9934594,
           listenings: 23053983,
           worldRanking: 267,
           description: """
            As they evolved from '90s French house pioneers to 2000s dance tastemakers to mainstream heroes in the 2010s, Daft Punk remained one of dance music's most iconic acts. With their early singles and 1997's instant-classic debut album Homework, Guy-Manuel de Homem-Christo and Thomas Bangalter quickly won acclaim for their skill at blending their beloved Chicago house and Detroit techno with pop, funk, indie rock, and hip-hop into nostalgic yet futuristic forms. Not content to just widen electronic music's popularity, on 2001's Discovery they reinvented the then-unfashionable sounds of mid-'80s soft rock and R&B into stylish tracks that also had a childlike wonder. Despite their sizable popularity, Daft Punk were never afraid to challenge their listeners, which they did with 2005's cold and dystopic Human After All. Even when they polarized their audience, there was never any doubt that they staged groundbreaking concerts, and the tour captured on Alive 2007 helped pave the way for arena-sized EDM, particularly in the U.S. With 2013's Random Access Memories, the duo once again looked to the past to create the future, borrowing from prog, disco, and a laid-back West Coast vibe that bucked the predominant trends in electronic music but still resonated with a wide audience. Daft Punk's influence reached further into the mainstream through collaborations with Kanye West and the Weeknd, and the duo's music was sampled by artists ranging from Missy Elliott to the Fall. Though they reinvented themselves continually, wherever Daft Punk went, the rest of pop music followed.
            
            After meeting in 1987 as students at Paris' Lycée Carnot secondary school, Bangalter and de Homem-Christo became friends and soon started making music together. In 1992, they formed the band Darlin'. Named after a Beach Boys song, the group featured Bangalter on bass, de Homem-Christo on guitar, and additional guitarist Laurent Brancowitz. Darlin's career was brief: The trio recorded a cover of their namesake song that appeared, along with an original song, on a various artists EP released by Stereolab's label Duophonic (the band also invited Darlin' to play some U.K. shows with them). Following a Melody Maker review that described Darlin's music as "a daft punky thrash," the band broke up. Bangalter and de Homem-Christo began experimenting with electronic music, taking their new project's name from that review and drawing inspiration from pioneers such as Todd Edwards, Juan Atkins, Kraftwerk, Frankie Knuckles, and many more.
            
            By September 1993, Daft Punk had readied a demo tape, which they gave to Soma co-founder Stuart MacMillan at a rave at EuroDisney. The label released the duo's debut single, "The New Wave," in April 1994. Instantly hailed by the dance music press as the work of a new breed of house innovators, it was followed by May 1995's "Da Funk," the band's first true hit (the record sold 30,000 copies worldwide and saw thorough rinsings by everyone from Kris Needs to the Chemical Brothers). In 1996, the buzz around Daft Punk led them to sign with , and the label released the single "Da Funk"/"Musique" that year. Recorded and mixed at the duo's Paris studio Daft House, January 1997's debut album Homework -- named for Daft Punk's D.I.Y. aesthetic -- was a critical and commercial success. The album reached number three in France and stayed on the chart for over a year, while the singles "Da Funk," "Around the World," "Burnin'," and "Revolution 909" charted in France, the U.K., the U.S., and Australia. The duo supported the record with the Daftendirekt tour, while the Homework video collection D.A.F.T.: A Story about Dogs, Androids, Firemen and Tomatoes followed in 1999 and featured clips directed by Roman Coppola, Michel Gondry, and Spike Jonze.
            """),
    Artist(name: "Michael Jackson", 
           image: "https://i.postimg.cc/sgWcj6GY/JACKSON.png",
           followers: 31510790,
           listenings: 41184528,
           worldRanking: 75,
           description: """
               Michael Jackson helped shape the sound and style of the 1970s and '80s and was one of the 20th century's defining stars, an artist and all-around entertainer who greatly informed pop culture on a global scale. The singer, songwriter, producer, and dancer rose to stardom at the dawn of the '70s as the prodigious focal point of the Jackson 5. Amid early success with the sibling Motown group, who would remain prominent for several years, Jackson branched out as a solo artist, and with "Ben" (1972) he topped the pop chart for the first of 13 times. A later starring role in The Wiz sparked a creative partnership with producer Quincy Jones. The first result was Off the Wall (1979), a dazzling disco-era album that announced Jackson as a mature talent with the number one hits "Don't Stop 'til You Get Enough" and "Rock with You." Determined to appeal to R&B, rock, and pop audiences at once, he responded with Thriller (1982). A harder-edged blockbuster proving that Jackson could sound both tender and tough, it crowned the Billboard chart for 37 weeks, earned eight Grammy Awards, and became the biggest-selling album of all time. Among its seven Top Ten singles were "Billie Jean" and "Thriller," cinematic songs promoted with groundbreaking music videos. "Billie Jean" was the first clip by a Black artist granted steady rotation on MTV, and at the Motown 25 celebration, Jackson's performance of that hit unveiled his signature dance move, the moonwalk, to a national audience. The high-tech follow-up Bad (1987) kept Jackson in the stratosphere by generating five number one singles. Dubbed "the King of Pop," Jackson then teamed with new jack swing originator Teddy Riley for Dangerous (1991), another worldwide hit. Four years later, HIStory paired a disc of hits with a new album highlighted by another number one single. Invincible (2001), a slick contemporary R&B set, extended Jackson's streak of number one albums but turned out to be the singer's last. Health problems culminated in his untimely death in 2009. Several posthumous releases have honored the true icon's legacy since then.
               
               Such heights came from modest beginnings. Michael was born in Gary, Indiana on August 29, 1958, the fifth son of Katherine and Joe Jackson. His mother was a Jehovah's Witness and his father a former boxer turned steelworker who played guitar on the side. Harboring aspirations of musical stardom, Joe shepherded his sons into a musical act around 1962. At that point, it was just the three eldest children -- Tito, Jackie, and Jermaine -- but Michael joined them in 1964 and soon dominated the group. Stealing moves from James Brown and Jackie Wilson, Michael became the epicenter of the Jackson 5 as they earned accolades at local talent shows and went on to play soul clubs throughout the Midwest, working their way toward the East Coast in 1967 where they won an amateur contest at the Apollo Theater. Returning to Gary, the group cut a pair of singles for the local imprint Steeltown in 1968 -- "(I'm A) Big Boy," "We Don't Have to Be Over 21" -- but their big break arrived when they opened for Bobby Taylor & the Vancouvers at Chicago's Regal Theater. Impressed, Taylor brought them to the attention of Berry Gordy, Jr., who signed the group to Motown in March 1969 and then sent them out to Los Angeles, where he helped mastermind their national launch.
               
               "I Want You Back," a song written and produced by Motown's new crew the Corporation, saw release in October 1968 when Michael Jackson was just 11 years old. By January 1970, "I Want You Back" rocketed to number one on both the pop and R&B charts, and the Jackson 5 became a sensation, crossing over from R&B to AM pop radio with ease. Two more hits followed --" ABC" and "The Love You Save," both exuberant bubblegum soul -- before "I'll Be There" revealed Michael's facility with ballads. All three of these sequels went to number one and, striking while the iron was hot, Motown spun Michael off into a solo act. His first solo single, "Got to Be There," arrived at the end of 1971, reaching number four on the Billboard Hot 100, and then a cover of Bobby Day's chestnut "Rockin' Robin" peaked at two in early 1972. Later that year, "Ben," the title theme ballad to an exploitation movie about a killer rat, earned Jackson his first Oscar nomination for Best Original Song (he would lose).
               """),
    Artist(name: "Toto",
           image: "https://i.postimg.cc/KYy5RPtd/TOTO.png",
           followers: 2940318,
           listenings: 29175041,
           worldRanking: 160,
           description: """
           Few ensembles in the history of recorded music have individually or collectively had a larger imprint on pop culture than the members of TOTO. As individuals, the band members can be heard on an astonishing 5000 albums that together amass a sales history of a half a billion albums. Amongst these recordings, NARAS applauded the performances with more than 200 Grammy nominations. Toto has over 400 million streams on Spotify alone along while views on YouTube far exceed over a half billion.
           
           With close to 40 years together and literally thousands of credits, including the biggest selling album of all time: Michael Jackson’s Thriller, and accolades to their names, TOTO remains one of the top selling touring and recording acts in the world. They are the benchmark by which many artists base their sound and production, and they continue to transcend the standards set by the entire music community, being simply synonymous with musical credibility. Their repertoire continues to be current via high profile usage on broadcast television. They are pop culture, and are one of the few 70’s bands that have endured the changing trends and styles to a career enjoy a multi-generational worldwide fan base.
           
           On February 9, 2018, TOTO will release their brand new Greatest Hits package 40 Trips Around The Sun featuring three new tracks.
           """),
    Artist(name: "Hologram Lo'",
           image: "https://i.postimg.cc/RVZMt5wX/HOLOGRAM-LO.jpg",
           followers: 11999,
           listenings: 112945,
           description: """
           A member of the group 1995 since early 2009, Hologram Lo', whose first name is Louis, is a French producer and composer from Paris born on 17 April 1990, working both solo and in collaboration with other French rap artists. As a solo artist, he has currently released four projects: 925 in 2012 and Deeplodocus in October 2014. On 10 November 2014, he released Innercity, his project in full collaboration with Darryl Zeuja, a rapper and member of the group 1995. On 7 August 2015 Lexus was released, followed on 11 July 2016 by Jeep, two entirely instrumental projects. In 2013, he co-created his own label, Don Dada Records, with Alpha Wann and Marguerite du Bled.
           """),
    Artist(name: "Kool & The Gang",
           image: "https://i.postimg.cc/yYgms5Wr/Kool-And-The-Gang.png",
           followers: 2489739,
           listenings: 8296219,
           description: """
           Formed as a jazz ensemble in the mid-'60s, Kool & the Gang became one of the most inspired and influential funk units during the '70s, and one of the most popular R&B groups of the '80s after their breakout hit "Celebration." Just as funky as James Brown or Parliament (and sampled almost as frequently), Kool & the Gang relied on their jazz backgrounds and long friendship to form a tightly knit group with the interplay and improvisation of a jazz outfit, plus the energy and spark of a band with equal ties to soul, R&B, and funk. Their 21 Top 40 hits exhibit an uncommon range, from the tough funk of "Jungle Boogie" to the smooth instrumental soul of "Summer Madness" to the lively pop of "Joanna." As an album act, they've been just as successful, having hit the Top Ten of the R&B chart with a dozen LPs that include the gold Wild and Peaceful (1973), the all-platinum run of Ladies' Night (1979), Celebrate! (1980), Something Special (1981), and Emergency (1984), and the gold Forever (1986). Since the '90s, they've focused most on touring, though they've occasionally put together sets of original material such as Still Kool (2007), Perfect Union (2021), and People Just Wanna Have Fun (2023). Fellow co-founders Robert "Kool" Bell and George "Funky" Brown continued to lead the band into the 2020s.
           
           Robert "Kool" Bell (aka Muhammad Bayyan) and his brother Ronald (aka Khalis Bayyan) grew up in Jersey City and picked up the music bug from their father, who was a professional boxer, serious jazz lover, and close friend of Thelonious Monk. With Robert on bass and Ronald picking up an array of horns, the duo formed the Jazziacs in 1964 with several neighborhood friends: guitarist Claydes Smith, trumpeter Robert "Spike" Mickens, alto saxophonist Dennis "D.T." Thomas, keyboard player Ricky West (aka Richard Westfield), and drummer George "Funky" Brown. The growing earthiness of soul inspired the Jazziacs to temper their jazz sensibilities with rhythms more akin to R&B, and the newly renamed Soul Town Band began playing clubs in Greenwich Village. After a mix-up with a club owner resulted in the group being billed Kool & the Flames, they modified the title to Kool & the Gang and found a leg up with the tiny De-Lite Records. Two singles from their self-titled debut album hit the pop chart, and although the positions weren't incredibly high, Kool & the Gang became a quick success on the R&B charts. Always a staple of their appeal, the group's live act was documented on two 1971 LPs, Live at the Sex Machine and Live at P.J.'s, including left-field covers of "Walk On By" and "Wichita Lineman" (as well as the not so unusual "I Want to Take You Higher").
           
           Studio albums followed in 1972 and 1973, but it was with Kool & the Gang's sixth LP, Wild and Peaceful, that they hit the big time. "Funky Stuff" became their first Top 40 hit at the end of 1973. Then both "Jungle Boogie" and "Hollywood Swinging" reached the Top Ten. Over the next four years, Kool & the Gang delivered a Grammy-nominated recording with Light of Worlds (in the category of Best R&B Instrumental Performance) and scored the Top 40 hits "Higher Plane" and "Spirit of the Boogie." They lost Ricky West to a solo flight and added some of their longest-serving brass players, namely trumpeter Larry Gittens and trombonist Clifford Adams. Also during this period, "Open Sesame" appeared on the Grammy-winning Saturday Night Fever soundtrack, yet the rise of disco -- a movement centered around producers and vocalists, in direct contrast to the group's focus on instrumentalists -- appeared to end their popularity.
           """),
    Artist(name: "Stromae",
           image: "https://i.postimg.cc/J4fbnqk7/Stromae.png",
           followers: 3315814,
           listenings: 11894843,
           description: """
           Paul Van Haver (Stromae) is a Belgian born artist, writer, performer, producer, designer and director. In 2009, he founded his own label "Mosaert", accompanied by his creative director Luc Van Haver, to mark the launch of his first album “Cheese”. Since the beginning of his career, he wanted to produce his own music as a way to maintain greater artistic independence. This means that his label will oversee everything: production, artistic direction, stage design, visuals, music videos and the stage costumes. In 2012, he met Coralie Barbier, a Belgian fashion designer. Her arrival would mark a turning point in Stromae's way of dressing. His second album, "Racine Carrée", released in 2014, encountered an unexpected level of success and became a great adventure which lasted 3 years. 5 million copies were sold across the world. His music videos reached one billion total views on Youtube. He did 209 live concerts attended by over 1.7 million people in Europe, North America, South America and Africa. In 2014, taking inspiration from Stromae’s costumes, the trio decided to launch a clothing line under the same name (Mosaert). After a 8 years hiatus, Stromae comes back in 2022 with a third studio album called « Multitude ». The twelve track full length was composed by Stromae and produced by his creative label Mosaert. Stromae is currently touring in Europe and the US to present his brand new show, the "Multitude Tour". Tickets: www.stromae.com
           """),
]

let featuringArtists: [Artist] = [
    Artist(name: "Pharell Williams"),
    Artist(name: "Nile Rodgers"),
    Artist(name: "Nemir"),
    Artist(name: "S.Pri Noir"),
    Artist(name: "Huntril"),
]
